import './styles.css';

const values = ['own', 'grow', 'prosper', 'better'];
const fundingAmounts = [25, 50, 75, 100, 150, 200, 300, 400, 500, 600];
const suitability = ['Class B Shares are non-voting shares.','Dividends are discretionary.','Capital growth is not guaranteed.','The investment is long-term.','Shares may be difficult to sell.','Solidus does not guarantee liquidity.','Solidus does not guarantee share buy-backs.','Tokenisation may never occur.','I may lose part or all of my investment.','I have read the Investment Memorandum.','I have read the Subscription Agreement.','I have read the Risk Disclosure Statement.'];
const amlStatements = ['Funds are not proceeds of crime.','Funds do not originate from money laundering.','Funds are not linked to terrorism financing.','Information provided is true and correct.','I agree to provide additional information if requested.'];
const documentsByType = {
  Individual: ['Certified ID Copy','Proof of Address (less than 3 months)','Proof of Bank Account','Tax Number Confirmation','Proof of Payment','Source of Funds Declaration'],
  Company: ['CIPC Registration Documents','Directors Register','Beneficial Ownership Information','Tax Clearance (if applicable)','Proof of Business Address','Company Bank Confirmation','Resolution Authorising Investment','Proof of Payment'],
  Trust: ['Trust Deed','Letter of Authority','Trustee IDs','Beneficial Ownership Information','Proof of Address','Proof of Payment']
};
const kasiIcon = {
  arrowRight: '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.25" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></svg>',
  arrowLeft: '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.25" stroke-linecap="round" stroke-linejoin="round"><path d="m12 19-7-7 7-7"/><path d="M19 12H5"/></svg>',
  check: '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.25" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 4 4L19 6"/></svg>',
  close: '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.25" stroke-linecap="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>'
};

const app = document.querySelector('#app');
app.innerHTML = `
<main class="campaign-shell">
  <div class="ambient ambient-one"></div><div class="ambient ambient-two"></div>
  <header class="site-header"><a class="brand-logo" href="#top" aria-label="KaSiShares home"><img src="/kasishares-logo.png" alt="KaSiShares — Own. Grow. Prosper. Together." /></a><div class="settlement"><span class="wallet-icon">▱</span> USDT settlement</div></header>
  <section class="campaign-grid" id="top">
    <article class="campaign-story">
      <div class="eyebrow"><span>▣</span> Private presale</div><p class="kicker">KaSiShares founding allocation</p><h1>Own a stake in the ecosystem we are building together.</h1><p class="lead">Reserve your KaSiShares allocation through a controlled private presale. Review the campaign terms before any payment is made.</p>
      <figure class="values-grid" aria-label="KaSiShares values">${values.map(name => `<img src="/kasishares-${name}.png" alt="${name[0].toUpperCase() + name.slice(1)}." />`).join('')}</figure>
      <div class="metric-grid" aria-label="Campaign details"><div class="metric"><span>Price per paid share</span><strong>1 USDT</strong></div><div class="metric"><span>Settlement quote</span><strong>1 USDT</strong></div><div class="metric"><span>Maximum allocation</span><strong>1,000 shares</strong></div><div class="metric"><span>Network</span><strong>BNB Smart Chain</strong></div></div>
      <div class="separation-card"><div class="shield">◇</div><div><h2>Clean separation by design</h2><p>Campaign reservations remain separate from the live share ledger. A reservation records intent only; it is not a final share certificate or proof of ownership.</p></div></div>
      <div class="process"><div><span>01</span><p><strong>Apply</strong>Complete the investor application in short phases.</p></div><div><span>02</span><p><strong>Verify</strong>KYC/FICA and compliance information is reviewed.</p></div><div><span>03</span><p><strong>Settle</strong>Approved applicants receive controlled payment instructions.</p></div></div>
    </article>
    <aside class="reservation-panel">
      <div class="panel-heading"><div><p class="panel-label">Investor application</p><h2 id="phase-title">Tell us about you</h2></div><span class="status-dot">Campaign preview</span></div>
      <div class="phase-progress"><div class="phase-progress-copy"><span id="phase-count">Step 1 of 6</span><strong id="phase-name">Investor</strong></div><div class="phase-track"><span id="phase-track-fill"></span></div><div class="phase-dots">${Array.from({length:6},(_,i)=>`<span class="${i===0?'active':''}"></span>`).join('')}</div></div>
      <p class="panel-intro" id="phase-intro">Start with the applicant type and primary contact details.</p>
      <form id="investor-application" novalidate>
        <section class="form-phase active" data-phase="1">
          <fieldset class="choice-grid investor-type"><legend>Applicant type</legend>${[['Individual','Apply in your own name'],['Company','Apply through a registered entity'],['Trust','Apply through a trust']].map(([type,help],i)=>`<label class="choice-card"><input type="radio" name="investor-type" value="${type}" ${i===0?'checked':''}/><span><strong>${type}</strong><small>${help}</small></span></label>`).join('')}</fieldset>
          <div class="field-grid"><label><span id="name-label">Full names</span><input id="full-name" autocomplete="name" required placeholder="Enter the applicant's legal name" /></label><label id="surname-field">Surname<input id="surname" autocomplete="family-name" required placeholder="Enter surname" /></label><label><span id="identity-label">ID / Passport number</span><input id="identity-number" required placeholder="Enter the official number" /></label><label>Email address<input id="email" type="email" autocomplete="email" required placeholder="you@example.com" /></label><label>Mobile number<input id="phone" type="tel" autocomplete="tel" required placeholder="+27 82 123 4567" /></label><label>Tax number<input id="tax-number" required placeholder="Enter tax number" /></label><label class="full-field">Physical / registered address<textarea id="physical-address" rows="3" required placeholder="Street, suburb, city and postal code"></textarea></label></div>
          <div class="entity-fields" hidden><p class="field-section-title">Authorised representative</p><div class="field-grid"><label>Name<input id="representative-name" placeholder="Representative's full name" /></label><label>Position<input id="representative-position" placeholder="Position or capacity" /></label><label>ID number<input id="representative-id" placeholder="Representative's ID" /></label><label>Registration number<input id="registration-number" placeholder="Entity registration number" /></label></div></div>
        </section>
        <section class="form-phase" data-phase="2" hidden>
          <fieldset class="funding-phases"><legend>Funding phase</legend>${fundingAmounts.map((amount,i)=>`<label><input type="radio" name="funding-phase" value="${i+1}" data-amount="${amount}" ${i===0?'checked':''}/><span>Phase ${i+1}<strong>USD $${amount}</strong></span></label>`).join('')}</fieldset>
          <div class="field-grid"><label>Number of shares<input id="shares" type="number" min="1" max="1000" value="25" required /></label><label>Price per share<input value="1 USDT" readonly /></label><label class="full-field">ZAR equivalent <span>(if applicable)</span><input id="zar-equivalent" inputmode="decimal" placeholder="R 0.00" /></label></div><div class="quote-row"><span>Total investment amount</span><strong id="quote">25 USDT</strong></div><p class="phase-note">Submission does not guarantee acceptance. Applications remain subject to EXCO approval, compliance, KYC/FICA, applicable legislation and share availability.</p>
        </section>
        <section class="form-phase" data-phase="3" hidden>
          <label>Source of funds<select id="source-of-funds" required><option value="">Select a source</option>${['Salary Income','Business Income','Investment Income','Property Sale','Inheritance','Pension','Savings','Company Funds','Trust Funds','Other'].map(item=>`<option>${item}</option>`).join('')}</select></label><label id="funds-other-field" hidden>Specify other source<input id="funds-other" placeholder="Describe the source of funds" /></label>
          <fieldset class="choice-grid funds-owner"><legend>The funds invested are</legend>${['My own funds','Company funds','Trust funds','Other'].map((item,i)=>`<label class="choice-card"><input type="radio" name="fund-owner" value="${item}" ${i===0?'checked':''}/><span><strong>${item}</strong></span></label>`).join('')}</fieldset>
          <p class="field-section-title">Investor banking details</p><div class="field-grid"><label>Account holder<input id="account-holder" required /></label><label>Bank<input id="bank" required /></label><label>Branch<input id="branch" required /></label><label>Account number<input id="account-number" inputmode="numeric" required /></label><label>Account type<select id="account-type" required><option value="">Select account type</option><option>Cheque / Current</option><option>Savings</option><option>Business</option><option>Trust</option></select></label><label>SWIFT code <span>(international only)</span><input id="swift-code" /></label></div>
        </section>
        <section class="form-phase" data-phase="4" hidden><div class="document-list" id="document-list"></div><label class="upload-field">Attach available supporting documents<input id="kyc-files" type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.doc,.docx"/><span>PDF, PNG, JPG or DOCX. Files remain on this device in preview mode.</span></label></section>
        <section class="form-phase" data-phase="5" hidden>
          <details class="disclosure" open><summary>Investor suitability and risk confirmations</summary><div class="check-list">${suitability.map(item=>`<label class="consent"><input type="checkbox" required/><span>${item}</span></label>`).join('')}</div></details>
          <fieldset class="choice-grid beneficial-owner"><legend>Beneficial owner declaration</legend><label class="choice-card"><input type="radio" name="beneficial-owner" value="self" checked/><span><strong>I am the beneficial owner</strong></span></label><label class="choice-card"><input type="radio" name="beneficial-owner" value="other"/><span><strong>I am acting on behalf of another person</strong></span></label></fieldset><label id="beneficial-owner-name" hidden>Person represented<input id="represented-person" placeholder="Full legal name"/></label>
          <div class="field-grid"><label>Country of tax residence<input id="tax-residence" required/></label><label>Tax Identification Number (TIN)<input id="tin" required/></label><label class="full-field">Additional tax jurisdictions <span>(if applicable)</span><input id="additional-tax-jurisdictions"/></label></div>
          <details class="disclosure"><summary>Anti-money laundering declaration</summary><div class="check-list">${amlStatements.map(item=>`<label class="consent"><input type="checkbox" required/><span>${item}</span></label>`).join('')}</div></details>
        </section>
        <section class="form-phase" data-phase="6" hidden>
          <div class="review-summary" id="application-summary"></div><div class="declaration-copy"><p>I apply for the Class B Shares specified in this application and confirm that the information supplied is true and correct.</p><p>I accept the risks associated with this investment, confirm that I am investing voluntarily, have obtained independent advice where required, and agree to be bound by the Company's MOI and governing documents.</p></div><label class="consent"><input id="final-declaration" type="checkbox" required/><span>I confirm this investor declaration and understand that final acceptance remains subject to Solidus Holdings (Pty) Ltd review and approval.</span></label><div class="field-grid"><label>Investor name<input id="signature-name" required placeholder="Type your full name"/></label><label>Date<input id="signature-date" type="date" required/></label><label class="full-field">Place<input id="signature-place" required placeholder="City or town"/></label></div><p class="phase-note">Typing your name records a preview acknowledgement only. A production electronic-signature process is not connected.</p>
        </section>
        <div class="phase-error" id="phase-error" role="alert"></div><div class="phase-actions"><button class="kasi-action back-button" data-kasi-tone="blue" id="phase-back" type="button" hidden><span>Back</span>${kasiIcon.arrowLeft}</button><button class="kasi-action reserve-button" id="phase-next" type="button"><span>Continue</span>${kasiIcon.arrowRight}</button><button class="kasi-action reserve-button" id="phase-submit" type="submit" hidden><span>Review application</span>${kasiIcon.check}</button></div>
      </form><div class="security-line"><span>◈</span> Section 10 investor application · KYC/FICA phased for mobile completion</div>
    </aside>
  </section>
  <footer><span>KaSiShares</span><p>Private campaign preview. Final issuer, eligibility, legal and settlement terms require approval before launch.</p></footer>
  <div class="review-overlay" id="review-overlay" hidden><section class="review-card" role="dialog" aria-modal="true" aria-labelledby="review-title"><button class="close-review" type="button" aria-label="Close review">${kasiIcon.close}</button><div class="review-icon">${kasiIcon.check}</div><p class="panel-label">Application preview ready</p><h2 id="review-title">Ready for compliance review</h2><p id="review-copy"></p><div class="review-warning">Backend submission, document upload and payment instructions are intentionally disabled until Wimpie's approved integration is connected.</div><button class="kasi-action secondary-button close-action" data-kasi-tone="blue" type="button"><span>Return to application</span>${kasiIcon.arrowLeft}</button></section></div>
</main>`;

const form=document.querySelector('#investor-application'); const phases=[...document.querySelectorAll('.form-phase')]; const overlay=document.querySelector('#review-overlay'); const phaseError=document.querySelector('#phase-error'); const nextButton=document.querySelector('#phase-next'); const backButton=document.querySelector('#phase-back'); const submitButton=document.querySelector('#phase-submit'); const sharesInput=document.querySelector('#shares');
const titles=['Tell us about you','Choose your investment','Funds and banking','Prepare your documents','Confirm declarations','Review and acknowledge']; const names=['Investor','Investment','Funds','KYC / FICA','Declarations','Review']; const intros=['Start with the applicant type and primary contact details.','Choose the funding phase and confirm the share allocation.','Declare where the investment funds come from and provide banking details.','Use the checklist to prepare documents for your applicant type.','Review the suitability, beneficial ownership, tax and AML declarations carefully.','Check the summary and record the applicant acknowledgement.']; let currentPhase=1;
const investorType=()=>form.elements['investor-type'].value;
function updateQuote(){const shares=Math.min(1000,Math.max(1,Number(sharesInput.value)||1));document.querySelector('#quote').textContent=`${shares.toLocaleString()} USDT`;}
function renderDocuments(){const type=investorType();document.querySelector('#document-list').innerHTML=`<p class="field-section-title">${type} investor documents</p>${documentsByType[type].map(item=>`<label class="document-check"><input type="checkbox"/><span>${item}</span></label>`).join('')}`;}
function updateInvestorType(){const type=investorType();const individual=type==='Individual';document.querySelector('.entity-fields').hidden=individual;document.querySelector('#surname-field').hidden=!individual;document.querySelector('#surname').required=individual;document.querySelector('#name-label').textContent=individual?'Full names':`${type} name`;document.querySelector('#identity-label').textContent=individual?'ID / Passport number':'Registration / authority number';['representative-name','representative-position','representative-id','registration-number'].forEach(id=>document.querySelector(`#${id}`).required=!individual);renderDocuments();}
function buildSummary(){const count=Math.min(1000,Math.max(1,Number(sharesInput.value)||1));const name=document.querySelector('#full-name').value;document.querySelector('#application-summary').innerHTML=`<p class="field-section-title">Application summary</p><dl><div><dt>Applicant</dt><dd>${name||'Not supplied'}</dd></div><div><dt>Applicant type</dt><dd>${investorType()}</dd></div><div><dt>Funding phase</dt><dd>Phase ${form.elements['funding-phase'].value}</dd></div><div><dt>Shares applied for</dt><dd>${count.toLocaleString()}</dd></div><div><dt>Total amount</dt><dd>${count.toLocaleString()} USDT</dd></div><div><dt>Source of funds</dt><dd>${document.querySelector('#source-of-funds').value||'Not supplied'}</dd></div></dl>`;document.querySelector('#signature-name').value||=`${name} ${document.querySelector('#surname').value}`.trim();document.querySelector('#signature-date').value||=new Date().toISOString().slice(0,10);}
function showPhase(number){currentPhase=number;phases.forEach((phase,i)=>{phase.hidden=i+1!==number;phase.classList.toggle('active',i+1===number);});document.querySelector('#phase-title').textContent=titles[number-1];document.querySelector('#phase-name').textContent=names[number-1];document.querySelector('#phase-count').textContent=`Step ${number} of 6`;document.querySelector('#phase-intro').textContent=intros[number-1];document.querySelector('#phase-track-fill').style.width=`${number/6*100}%`;document.querySelectorAll('.phase-dots span').forEach((dot,i)=>dot.classList.toggle('active',i<number));backButton.hidden=number===1;nextButton.hidden=number===6;submitButton.hidden=number!==6;phaseError.textContent='';if(number===6)buildSummary();document.querySelector('.reservation-panel').scrollIntoView({behavior:'smooth',block:'start'});}
function validatePhase(){const invalid=[...phases[currentPhase-1].querySelectorAll('[required]')].filter(field=>!field.closest('[hidden]')).find(field=>!field.checkValidity());if(!invalid)return true;phaseError.textContent='Complete the highlighted field before continuing.';invalid.reportValidity();invalid.focus();return false;}
form.elements['investor-type'].forEach(input=>input.addEventListener('change',updateInvestorType));form.elements['funding-phase'].forEach(input=>input.addEventListener('change',event=>{sharesInput.value=event.target.dataset.amount;updateQuote();}));form.elements['beneficial-owner'].forEach(input=>input.addEventListener('change',()=>{const other=form.elements['beneficial-owner'].value==='other';document.querySelector('#beneficial-owner-name').hidden=!other;document.querySelector('#represented-person').required=other;}));document.querySelector('#source-of-funds').addEventListener('change',event=>{const other=event.target.value==='Other';document.querySelector('#funds-other-field').hidden=!other;document.querySelector('#funds-other').required=other;});sharesInput.addEventListener('input',updateQuote);nextButton.addEventListener('click',()=>{if(validatePhase())showPhase(Math.min(6,currentPhase+1));});backButton.addEventListener('click',()=>showPhase(Math.max(1,currentPhase-1)));
form.addEventListener('submit',event=>{event.preventDefault();if(!validatePhase())return;const shares=Math.min(1000,Math.max(1,Number(sharesInput.value)||1));const name=document.querySelector('#signature-name').value.trim();document.querySelector('#review-copy').textContent=`${name}, your Class B Share application preview covers ${shares.toLocaleString()} shares for ${shares.toLocaleString()} USDT. No application has been transmitted.`;overlay.hidden=false;document.body.classList.add('dialog-open');});
function closeReview(){overlay.hidden=true;document.body.classList.remove('dialog-open');}document.querySelectorAll('.close-review,.close-action').forEach(button=>button.addEventListener('click',closeReview));overlay.addEventListener('click',event=>{if(event.target===overlay)closeReview();});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeReview();});updateInvestorType();updateQuote();showPhase(1);
